// Generated by CoffeeScript 1.12.7
(function() {
  var myFunc, myObject, myVar;

  myFunc = function(hello, callback) {
    return callback("nope");
  };

  myFunc("hello", function(cb_param) {
    return console.log(cb_param);
  });

  myVar = 2;

  myObject = {
    prop1: "hello",
    prop2: 2
  };

  if (err) {
    throw err;
  }

}).call(this);
