// Generated by CoffeeScript 1.12.7
(function() {
  module.exports = {
    save: function(name, pwd, callback) {
      if (callback === void 0) {
        callback = pwd;
        return callback(new Error("missing parameters"));
      } else {
        console.log("saving " + name + " with pwd " + pwd);
        return callback();
      }
    },
    get: function(name, callback) {
      console.log("saving " + name);
      return callback();
    }
  };

}).call(this);
